src/join.sol

Makes `exit` compatible with many ERC20s, not just ds-tokens.

Use transfer in exit instead of transferFrom

---

src/vat.sol

Rename a Vat.slip arg from `rad` to `wad` that should have been renamed in [an earlier commit](https://github.com/makerdao/dss/commit/285086d59e899fcdabb289d18660d654aad57e5f).

rename slip's quantity arg to wad

---

src/flop.sol
src/test/flop.t.sol
src/test/vat.t.sol
src/test/vow.t.sol
src/vow.sol

Currently Vow uses `uint(-1)` as the starting point for Flop auctions.  This is:
1) a huge but arbitrary number
2) will cause the auction to fail if there are no bids as it is not possible to mint uint(-1) new MKR because `totalSupply` would overflow
3) it opens the possibility of low bidder participation minting a huge amount of MKR.
This introduces `Vow.dump` which would be the governance-controlled variable for how much `lot` (i.e. MKR gems) the Flop auction should start with. The `dump` replaces `uint(-1)` as the ceiling from which to start the `Flop`/`dent` auctions. If bidders do not feel this amount is worth the asking `bid` and the auction expires with 0 bids, then `tick` will increase the `lot` by `beg` and restart the auction.
Benefits of this approach:
- Since it is governance …

Flop varying sized mkr lots

---

.travis.yml
src/cat.sol
src/dai.sol
src/end.sol
src/flap.sol
src/flip.sol
src/flop.sol
src/join.sol
src/jug.sol
src/lib.sol
src/pot.sol
src/spot.sol
src/test/dai.t.sol
src/test/end.t.sol
src/test/flap.t.sol
src/test/flip.t.sol
src/test/flop.t.sol
src/test/fork.t.sol
src/test/jug.t.sol
src/test/pot.t.sol
src/test/vat.t.sol
src/test/vow.t.sol
src/vat.sol
src/vow.sol

This PR locks solidity to a very specific version `0.5.11` in preparation for deployment.  We wanted to make sure it was at least `0.5.7` to fix bugs in `ABIEncoderV2`.  We discussed locking to `0.5.9` for `klab`, and ultimately decided to lock to `0.5.11`.

ISSUE-335: Explicitly declare compiler version

---

.travis.yml
src/cat.sol
src/dai.sol
src/end.sol
src/flap.sol
src/flip.sol
src/flop.sol
src/join.sol
src/jug.sol
src/lib.sol
src/pot.sol
src/spot.sol
src/test/dai.t.sol
src/test/end.t.sol
src/test/flap.t.sol
src/test/flip.t.sol
src/test/flop.t.sol
src/test/fork.t.sol
src/test/jug.t.sol
src/test/pot.t.sol
src/test/vat.t.sol
src/test/vow.t.sol
src/vat.sol
src/vow.sol

Since the `=` operator is assumed if just given the pragma, we will just remove it.  The only change here is to make the pragma line more sexy.

ISSUE-335-02: remove = operator as it's the default

---

src/dai.sol

Solidity 0.5.x still compiles constants as pure functions, which executes on every access

Avoid keccak256 in constant

---

src/pot.sol

hey,
I noticed in the `pot.drip` method the addition `chi = add(chi, chi_);` is more expensive than just to store the latest chi (calculated already in the previous line).
Improvement is around `~600 gas` per method call.
Since the method should be called very often. I think it makes sense to change it.
**Current Gas**
```
Running 7 tests for src/test/pot.t.sol:DSRTest
[PASS] testFail_stale_chi() (gas: 145165)
[PASS] test_drip_multi() (gas: 549591)
[PASS] test_drip_multi_inBlock() (gas: 375922)
[PASS] test_fresh_chi() (gas: 457704)
[PASS] test_save_0d() (gas: 454693)
[PASS] test_save_1d() (gas: 522272)
[PASS] test_save_multi() (gas: 761726)
```
**Improvement Gas**
```
Running 7 tests for src/test/pot.t.sol:DSRTest
[PASS] testFail_stale_chi() (gas: 144631)
[PASS] test_drip_multi() (gas: …
```

more gas efficient implementation of pot.drip

---

src/vat.sol

This flips args of `mul()` for some small gas savings.  We know from line `169` that `ilk.rate` can never be `0`; however, there are many potential times `urn.art` will be `0`.  In the implementation of `mul()` on line `114` we short-circuit the `require()` if `y == 0` thus saving some gas.
**bonus**: The readability is slightly better because of how the arguments are ordered in the call above.
This may be too small an optimization too late in the cycle, but we thought we would bring it up.  Feel free to close.

restructuring mul() call

---

src/cat.sol
src/dai.sol
src/end.sol
src/flap.sol
src/flip.sol
src/flop.sol
src/join.sol
src/jug.sol
src/lib.sol
src/pot.sol
src/spot.sol
src/test/dai.t.sol
src/test/end.t.sol
src/test/flap.t.sol
src/test/flip.t.sol
src/test/flop.t.sol
src/test/fork.t.sol
src/test/jug.t.sol
src/test/pot.t.sol
src/test/vat.t.sol
src/test/vow.t.sol
src/vat.sol
src/vow.sol

Updates DSS pragma's to floating 0.5.12 so contracts integrating and testing against DSS aren't forced to compile with 0.5.12.

Update pragma to floating 0.5.12

---

src/jug.sol

We forgot to add the copyright header to `jug.sol`.
I also chose the name `Dai Lending Rate`, to match the counter part in `pot.sol` of `Dai Savings Rate`.

SC-4319: adds copyright header to jug.sol

---

src/cat.sol
src/flip.sol
src/test/end.t.sol
src/test/flip.t.sol
src/test/vat.t.sol

This PR adds support to limit the amount of on-auction Dai.
Governance sets the variable `box` to be the maximum amount of Dai out for auction at any given time.  As under-collateralized Vaults are sent to auction, an accumulator `litter` is incremented.  Once the `litter` fills the `box`, the `cat` can no longer `bite` thus pausing liquidations.  As Dai is reclaimed in `flip` auctions, `scoop()` is called to decrement the `litter` in the `box`; thus making room for more liquidations.

SC-4900: support to limit on-auction DAI

---

src/dog.sol

Since `dart <= art`, we don't need to check `min` since `dink = ink` when `dart = art`.
Gas calculations:
```
360644 - full hole, old
360569 - full hole, new
75 - gas savings
358067 - partial hole, old
357982 - partial hole, new
85 - gas savings
```

refactor: Minor `dink` Gas Optimization

---

src/clip.sol
src/dog.sol
src/end.sol

- Changes `10 ** 9` to `BIL`
- Remove whitespace

Liq-2.0: remove some whitespace and change to BIL

---

Makefile
src/abaci.sol
src/clip.sol
src/dog.sol

- updates some comments with
- fix Makefile
- adds missing events
- `now` to `block.timestamp`
- TODO

LIQ-2.0 20210114 updates

---

src/clip.sol
src/dog.sol
src/test/clip.t.sol
src/test/end.t.sol

Overloads the bark function so that a keeper can send the rewards to a different address.

Add extra function to pay rewards to external address

---

src/clip.sol
src/dog.sol
src/test/clip.t.sol
src/test/end.t.sol

This fixes a bug where we missed incentives in `redo()` by moving incentives into the `clip.kick()` and `clip.redo()`.  The variables `chip` and `tip` were also moved to each ilk's respective `Clipper`.
The biggest methodology change is that rather than calculating the `tip` and `chip` on the normalized debt owed, we are calculating it on the entire `tab`.  Calculating these values on the normalized debt in `kick()` would require passing the normalized debt to `kick()` and then storing it.  We would then need to store the original `tab` in order to calculate the ratio of initial tab to partial tab later in the `redo()` so that we could only incentivize the `redo()` on the leftover partial liquidation.
Rather than doing all of that, I'm suggesting we simply use the `tab` to calculate …

fix: move incentive to kick() in redo() (SC-8390)

---

src/dog.sol
src/test/dog.t.sol

Both Quantstamp and ToB have pointed to potential issues if `chop` is zero or just very small (e.g. liquidations being disabled). There's also a very strong correctness argument that it should never be less than `WAD` due to auction grinding. IMO in this case a little input validation is justified.

validation for chop

---

src/abaci.sol
src/test/abaci.t.sol

There are fair arguments that maybe the stairstep functionality is not really beneficial; while `step` could always be set to 1 in that case, it's more gas-efficient to have a separate function that won't do the pointless `SLOAD` if a continuous exponential proves preferable.

add continuous exponential decrease

---

src/dog.sol
src/test/dog.t.sol

Address a ToB finding. Collateral can become permanently stuck in a Clipper if it's for a different `ilk` than the immutable value the Clipper holds.

Validate ilk when filing clip in Dog

---

src/clip.sol
src/test/clip.t.sol

We corrected how `dust` was handled in the Dog, but not the Clipper, in the course of the audits. This PR shows what fully making this consistent looks like. It is maybe too late to put it in (as it's IMO a low severity issue, just an inconsistency that could occasionally lead to dusty amounts of collateral left by partial `takes`, which can happen anyway e.g. if a dusty Vault is liquidated), but I thought everyone should at least understand why the current code is inconsistent. If we launch with that inconsistency, it can potentially be corrected in Liq 2.1, which also gives us more time to refactor into a more gas-efficient format (a good argument against this change is that the small inconsistency is acceptable in order to reduce gas costs).

properly account for chop in dust checks in the Clipper

---

src/cure.sol
src/end.sol
src/test/cure.t.sol
src/test/end.t.sol

This PR makes the `cure` implementation closer to what you guys have been discussing. Do you think this way is a bit better?
It would be missing the control that every source is set after `cage` (which I'm still not sure if really needed)

Set only after cage, and force cage on End.cage
